# Turbofan Engines Engine Removal Forecast

## EDA Phase

""" Aircraft Turbofan Engines Engine Removal Forecast:
This notebook is the EDA phase for 16 turbofan Engines,
the ultimate goal of the complete project is to predict
the remaining useful life (RCL) of similar in-service engines """

In [1]:
# Import neccessary libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# load the data
df = pd.read_csv(r'Data/A320NEOMSRMSC_masked.csv', on_bad_lines='skip')

In [3]:
# Drop columns not used downstream
df = df.drop(columns=['CARRIER', 'AIRCRAFT_ID', 'EPOSITION'])

In [4]:
df.head(20)

,ESN,FLIGHT_PHASE,FLIGHT_DATETIME,AIRCRAFT_TYPE,ENGINE_FAMILY,ENGINE_TYPE,ENGINE_INSTALL_DATE,Cycles,Cycles_INIT_VALUE,Delta EGT,...,T3,T25,PS3 Selection Status,Delta Fan Speed,EGT Probe average,EGT Hot Day Margin Divergence Smoothed,Thrust Derate,Computed Air Speed,ZPS3,HPC Discharge Static Pressure PS3
0,ESN1,TAKEOFF,2024-03-02 09:30:59,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,563.0,NaN,NaN,...,NaN,NaN,NaN,NaN,890.2250,-3.4255,11.8218,88.0,470.42,NaN
1,ESN1,TAKEOFF,2025-09-06 07:23:51,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,1905.0,NaN,NaN,...,NaN,NaN,NaN,NaN,942.5750,-3.6070,10.9685,91.0,472.14,NaN
2,ESN1,CRUISE,2025-05-04 04:32:58,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,1500.0,NaN,14.4112,...,NaN,NaN,NaN,NaN,699.0500,NaN,NaN,252.0,166.74,NaN
3,ESN1,TAKEOFF,2025-12-17 09:57:31,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,2246.0,NaN,NaN,...,NaN,NaN,NaN,NaN,857.8000,-4.2556,19.3867,90.0,444.89,NaN
4,ESN1,TAKEOFF,2025-06-03 09:07:19,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,1598.0,NaN,NaN,...,NaN,NaN,NaN,NaN,850.2500,-1.8895,24.2619,87.0,416.71,NaN
5,ESN1,TAKEOFF,2025-10-13 15:58:02,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,2040.0,NaN,NaN,...,NaN,NaN,NaN,NaN,862.6000,-2.3097,23.9590,93.0,424.15,NaN
6,ESN1,TAKEOFF,2026-03-10 13:05:09,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,2471.0,NaN,NaN,...,NaN,NaN,NaN,NaN,871.4375,-3.7830,14.8586,94.0,456.53,NaN
7,ESN1,CRUISE,2025-10-10 08:39:27,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,2026.0,NaN,15.4168,...,NaN,NaN,NaN,NaN,721.3875,NaN,NaN,270.0,176.34,NaN
8,ESN1,CRUISE,2024-12-06 09:07:10,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,999.0,NaN,11.7764,...,NaN,NaN,NaN,NaN,694.1625,NaN,NaN,259.0,164.94,NaN
9,ESN1,TAKEOFF,2025-07-06 10:25:37,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,1706.0,NaN,NaN,...,NaN,NaN,NaN,NaN,884.4750,-1.9268,17.1895,95.0,449.31,NaN
10,ESN1,TAKEOFF,2026-01-01 16:31:39,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,2294.0,NaN,NaN,...,NaN,NaN,NaN,NaN,851.3125,-4.1177,21.4219,90.0,436.46,NaN
11,ESN1,TAKEOFF,2025-08-03 15:43:56,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,1789.0,NaN,NaN,...,NaN,NaN,NaN,NaN,899.1125,-2.2651,13.7105,87.0,462.99,NaN
12,ESN1,TAKEOFF,2024-09-04 21:38:12,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,746.0,NaN,NaN,...,NaN,NaN,NaN,NaN,845.8500,-5.5153,26.9530,91.0,407.14,NaN
13,ESN1,CRUISE,2026-04-05 21:52:18,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,2544.0,NaN,17.6000,...,NaN,NaN,NaN,NaN,787.3500,NaN,NaN,256.0,164.32,NaN
14,ESN1,CRUISE,2025-08-22 16:53:48,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,1852.0,NaN,10.3734,...,NaN,NaN,NaN,NaN,777.6875,NaN,NaN,258.0,172.77,NaN
15,ESN1,CRUISE,2025-12-09 16:54:24,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,2226.0,NaN,16.8854,...,NaN,NaN,NaN,NaN,706.7125,NaN,NaN,263.0,176.69,NaN
16,ESN1,CRUISE,2023-11-01 13:49:06,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,209.0,NaN,9.7811,...,NaN,NaN,NaN,NaN,699.7750,NaN,NaN,247.0,158.63,NaN
17,ESN1,CRUISE,2025-11-18 18:41:15,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,2165.0,NaN,20.1626,...,NaN,NaN,NaN,NaN,710.3750,NaN,NaN,272.0,186.27,NaN
18,ESN1,CRUISE,2025-01-08 21:39:32,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,1115.0,NaN,11.1351,...,NaN,NaN,NaN,NaN,717.0500,NaN,NaN,262.0,166.98,NaN
19,ESN1,TAKEOFF,2024-09-17 17:42:47,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,458.0,NaN,NaN,...,NaN,NaN,NaN,NaN,785.1375,NaN,26.4650,89.0,416.91,NaN

In [5]:
# Check the data statistics
df.describe()

,Cycles,Cycles_INIT_VALUE,Delta EGT,EGT Hot Day Margin,Indicated Air Speed,Fuel Flow,Calculated Fuel Flow,Oil Temperature,EGT Divergence,PS3 Divergence,...,T3,T25,PS3 Selection Status,Delta Fan Speed,EGT Probe average,EGT Hot Day Margin Divergence Smoothed,Thrust Derate,Computed Air Speed,ZPS3,HPC Discharge Static Pressure PS3
count,546280.000000,0.0,351627.000000,185275.000000,0.0,546219.000000,0.0,546273.000000,546053.000000,546062.000000,...,0.0,0.0,0.0,0.0,546214.000000,184262.000000,185921.000000,546273.000000,546261.000000,0.0
mean,1686.078042,NaN,15.427746,53.368633,NaN,2851.204132,NaN,88.648587,0.021624,-0.029804,...,NaN,NaN,NaN,NaN,777.644583,-0.057319,19.356520,205.026209,266.461716,NaN
std,1371.898276,NaN,10.121698,16.912307,NaN,1390.891739,NaN,8.014414,5.263138,1.518907,...,NaN,NaN,NaN,NaN,69.141159,5.596946,6.495689,83.969235,127.213128,NaN
min,0.000000,NaN,-481.606500,-7.553000,NaN,454.000000,NaN,0.000000,-456.550000,-205.490000,...,NaN,NaN,NaN,NaN,0.000000,-32.047300,-44.276000,0.000000,-110.000000,NaN
25%,646.000000,NaN,9.032500,40.780400,NaN,2214.000000,NaN,83.500000,-2.350000,-0.530000,...,NaN,NaN,NaN,NaN,727.162500,-3.222475,15.780300,91.000000,170.850000,NaN
50%,1275.000000,NaN,14.257700,57.069500,NaN,2401.000000,NaN,89.100000,0.050000,-0.015000,...,NaN,NaN,NaN,NaN,763.312500,0.073800,20.330200,254.000000,184.340000,NaN
75%,2477.000000,NaN,20.623000,66.997600,NaN,2804.000000,NaN,94.000000,2.450000,0.450000,...,NaN,NaN,NaN,NaN,835.312500,3.053300,24.445300,264.000000,418.340000,NaN
max,72590.000000,NaN,71.982000,92.445700,NaN,22222.000000,NaN,909.200000,456.550000,137.915000,...,NaN,NaN,NaN,NaN,1029.437500,23.042400,54.315800,346.000000,534.400000,NaN

In [6]:
# check data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 546310 entries, 0 to 546309
Data columns (total 39 columns):
 #   Column                                  Non-Null Count   Dtype
---  ------                                  --------------   -----
 0   ESN                                     546310 non-null  object
 1   FLIGHT_PHASE                            546310 non-null  object
 2   FLIGHT_DATETIME                         546310 non-null  object
 3   AIRCRAFT_TYPE                           546310 non-null  object
 4   ENGINE_FAMILY                           546310 non-null  object
 5   ENGINE_TYPE                             546310 non-null  object
 6   ENGINE_INSTALL_DATE                     546310 non-null  object
 7   Cycles                                  546280 non-null  float64
 8   Cycles_INIT_VALUE                       0 non-null       float64
 9   Delta EGT                               351627 non-null  float64
 10  EGT Hot Day Margin                      185275 non-null  float64
 11  Indicated Air Speed                     0 non-null       float64
 12  Fuel Flow                               546219 non-null  float64
 13  Calculated Fuel Flow                    0 non-null       float64
 14  Oil Temperature                         546273 non-null  float64
 15  EGT Divergence                          546053 non-null  float64
 16  PS3 Divergence                          546062 non-null  float64
 17  Oil Pressure                            546276 non-null  float64
 18  Oil Pressure Divergence                 546089 non-null  float64
 19  Core Speed                              546253 non-null  float64
 20  Core Speed Divergence                   546057 non-null  float64
 21  HPC Inlet Total Pres                    0 non-null       float64
 22  P25 Divergence                          0 non-null       float64
 23  HPC Discharge Total Pres                0 non-null       float64
 24  Pt2 (Fan Inlet Tot Pres)                546264 non-null  float64
 25  Engine Pressure Ratio Max               0 non-null       float64
 26  Engine Serial Number                    667 non-null     float64
 27  Hours                                   0 non-null       float64
 28  T5                                      0 non-null       float64
 29  T3                                      0 non-null       float64
 30  T25                                     0 non-null       float64
 31  PS3 Selection Status                    0 non-null       float64
 32  Delta Fan Speed                         0 non-null       float64
 33  EGT Probe average                       546214 non-null  float64
 34  EGT Hot Day Margin Divergence Smoothed  184262 non-null  float64
 35  Thrust Derate                           185921 non-null  float64
 36  Computed Air Speed                      546273 non-null  float64
 37  ZPS3                                    546261 non-null  float64
 38  HPC Discharge Static Pressure PS3       0 non-null       float64
dtypes: float64(32), object(7)
memory usage: 162.6+ MB

In [7]:
# Check for missing values, percentage
df.isnull().sum()/len(df)*100

ESN                                         0.000000
FLIGHT_PHASE                                0.000000
FLIGHT_DATETIME                             0.000000
AIRCRAFT_TYPE                               0.000000
ENGINE_FAMILY                               0.000000
ENGINE_TYPE                                 0.000000
ENGINE_INSTALL_DATE                         0.000000
Cycles                                      0.005491
Cycles_INIT_VALUE                         100.000000
Delta EGT                                  35.635994
EGT Hot Day Margin                         66.086105
Indicated Air Speed                       100.000000
Fuel Flow                                   0.016657
Calculated Fuel Flow                      100.000000
Oil Temperature                             0.006773
EGT Divergence                              0.047043
PS3 Divergence                              0.045395
Oil Pressure                                0.006224
Oil Pressure Divergence                     0.040453
Core Speed                                  0.010434
Core Speed Divergence                       0.046311
HPC Inlet Total Pres                      100.000000
P25 Divergence                            100.000000
HPC Discharge Total Pres                  100.000000
Pt2 (Fan Inlet Tot Pres)                    0.008420
Engine Pressure Ratio Max                 100.000000
Engine Serial Number                       99.877908
Hours                                     100.000000
T5                                        100.000000
T3                                        100.000000
T25                                       100.000000
PS3 Selection Status                      100.000000
Delta Fan Speed                           100.000000
EGT Probe average                           0.017572
EGT Hot Day Margin Divergence Smoothed     66.271531
Thrust Derate                              65.967857
Computed Air Speed                          0.006773
ZPS3                                        0.008969
HPC Discharge Static Pressure PS3         100.000000
dtype: float64

In [8]:
# delete features that have more than 50% missing values
null_50 = df.isnull().sum()/len(df)*100 > 50
null_50 = null_50[null_50].index
df = df.drop(null_50, axis=1)
df.head(20)

,ESN,FLIGHT_PHASE,FLIGHT_DATETIME,AIRCRAFT_TYPE,ENGINE_FAMILY,ENGINE_TYPE,ENGINE_INSTALL_DATE,Cycles,Delta EGT,Fuel Flow,...,EGT Divergence,PS3 Divergence,Oil Pressure,Oil Pressure Divergence,Core Speed,Core Speed Divergence,Pt2 (Fan Inlet Tot Pres),EGT Probe average,Computed Air Speed,ZPS3
0,ESN1,TAKEOFF,2024-03-02 09:30:59,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,563.0,NaN,1716.0,...,2.70,-3.720,91.4,2.45,106.45,-0.055,14.77,890.2250,88.0,470.42
1,ESN1,TAKEOFF,2025-09-06 07:23:51,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,1905.0,NaN,7425.0,...,4.10,-4.315,97.3,1.25,108.47,-0.080,14.11,942.5750,91.0,472.14
2,ESN1,CRUISE,2025-05-04 04:32:58,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,1500.0,14.4112,2230.0,...,2.25,-1.375,89.3,1.45,98.41,-0.015,4.72,699.0500,252.0,166.74
3,ESN1,TAKEOFF,2025-12-17 09:57:31,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,2246.0,NaN,6619.0,...,4.30,-3.965,101.8,-0.20,104.47,-0.130,15.08,857.8000,90.0,444.89
4,ESN1,TAKEOFF,2025-06-03 09:07:19,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,1598.0,NaN,6199.0,...,1.75,-3.575,91.5,2.05,104.82,-0.090,15.03,850.2500,87.0,416.71
5,ESN1,TAKEOFF,2025-10-13 15:58:02,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,2040.0,NaN,6322.0,...,1.50,-3.640,93.9,1.65,105.27,-0.080,15.01,862.6000,93.0,424.15
6,ESN1,TAKEOFF,2026-03-10 13:05:09,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,2471.0,NaN,6938.0,...,1.75,-3.205,104.9,0.65,105.24,-0.105,14.93,871.4375,94.0,456.53
7,ESN1,CRUISE,2025-10-10 08:39:27,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,2026.0,15.4168,2337.0,...,2.95,-1.425,86.5,2.05,100.66,-0.015,5.44,721.3875,270.0,176.34
8,ESN1,CRUISE,2024-12-06 09:07:10,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,999.0,11.7764,2157.0,...,4.25,-1.400,88.4,0.80,98.66,-0.025,4.97,694.1625,259.0,164.94
9,ESN1,TAKEOFF,2025-07-06 10:25:37,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,1706.0,NaN,6815.0,...,2.50,-5.385,93.6,0.20,106.22,-0.155,15.02,884.4750,95.0,449.31
10,ESN1,TAKEOFF,2026-01-01 16:31:39,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,2294.0,NaN,6445.0,...,3.85,-3.730,95.5,1.90,104.35,-0.075,15.17,851.3125,90.0,436.46
11,ESN1,TAKEOFF,2025-08-03 15:43:56,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,1789.0,NaN,7108.0,...,1.50,-4.190,94.6,2.45,106.56,-0.070,15.00,899.1125,87.0,462.99
12,ESN1,TAKEOFF,2024-09-04 21:38:12,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,746.0,NaN,2395.0,...,5.75,-3.455,91.6,2.50,104.56,-0.055,15.04,845.8500,91.0,407.14
13,ESN1,CRUISE,2026-04-05 21:52:18,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,2544.0,17.6000,2301.0,...,4.15,-1.405,89.1,2.25,103.10,-0.030,4.77,787.3500,256.0,164.32
14,ESN1,CRUISE,2025-08-22 16:53:48,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,1852.0,10.3734,2409.0,...,3.40,-1.425,91.1,5.40,102.77,-0.030,4.94,777.6875,258.0,172.77
15,ESN1,CRUISE,2025-12-09 16:54:24,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,2226.0,16.8854,2361.0,...,3.85,-1.505,92.6,1.35,98.72,-0.035,5.02,706.7125,263.0,176.69
16,ESN1,CRUISE,2023-11-01 13:49:06,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,209.0,9.7811,2087.0,...,1.75,-1.255,82.2,1.60,98.61,-0.020,4.53,699.7750,247.0,158.63
17,ESN1,CRUISE,2025-11-18 18:41:15,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,2165.0,20.1626,2482.0,...,3.10,-1.560,91.7,2.15,99.14,-0.030,5.29,710.3750,272.0,186.27
18,ESN1,CRUISE,2025-01-08 21:39:32,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,1115.0,11.1351,2207.0,...,4.00,-1.460,85.5,1.60,100.04,-0.020,5.01,717.0500,262.0,166.98
19,ESN1,TAKEOFF,2024-09-17 17:42:47,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,458.0,NaN,2847.0,...,3.65,-3.555,94.1,3.30,101.73,-0.060,14.94,785.1375,89.0,416.91

In [9]:
# lets rename the columns for easy access, replace space with underscore, and convert to lower case, and remove special characters, and remove the word 'engine', and make shorter names
df.columns = df.columns.str.replace(' ', '_').str.lower().str.replace('[-/()#]', '').str.replace('engine', 'eng').str.replace('temperature', 'temp').str.replace('pressure', 'pres').str.replace('vibration', 'vib').str.replace('speed', 'spd').str.replace('temperature', 'temp').str.replace('flow', 'flw')

In [10]:
df.columns

Index(['esn', 'flight_phase', 'flight_datetime', 'aircraft_type', 'eng_family',
       'eng_type', 'eng_install_date', 'cycles', 'delta_egt', 'fuel_flw',
       'oil_temp', 'egt_divergence_', 'ps3_divergence', 'oil_pres',
       'oil_pres_divergence', 'core_spd', 'core_spd_divergence',
       'pt2_(fan_inlet_tot_pres)', 'egt_probe_average', 'computed_air_spd',
       'zps3'],
      dtype='object')

In [11]:
# check how many engines in the data
df['esn'].unique()

array(['ESN1', 'ESN2', 'ESN3', 'ESN4', 'ESN5', 'ESN6', 'ESN7', 'ESN8',
       'ESN9', 'ESN10', 'ESN11', 'ESN12', 'ESN13', 'ESN14', 'ESN15',
       'ESN16', 'ESN17', 'ESN18', 'ESN19', 'ESN20', 'ESN21', 'ESN22',
       'ESN23', 'ESN24', 'ESN25', 'ESN26', 'ESN27', 'ESN28', 'ESN29',
       'ESN30', 'ESN31', 'ESN32', 'ESN33', 'ESN34', 'ESN35', 'ESN36',
       'ESN37', 'ESN38', 'ESN39', 'ESN40', 'ESN41', 'ESN42', 'ESN43',
       'ESN44', 'ESN45', 'ESN46', 'ESN47', 'ESN48', 'ESN49'], dtype=object)

In [12]:
# make a dictionary of engines types and numbers for each type
eng_types = df['eng_type'].unique()
eng_numbers = {}
for eng in eng_types:
    eng_numbers[eng] = df[df['eng_type'] == eng]['esn'].unique()
eng_numbers

{'LEAP-1A26': array(['ESN1', 'ESN2', 'ESN4', 'ESN5', 'ESN7', 'ESN9', 'ESN12', 'ESN14',
        'ESN15', 'ESN16', 'ESN18', 'ESN20', 'ESN21', 'ESN23', 'ESN28',
        'ESN29', 'ESN30', 'ESN31', 'ESN33', 'ESN34', 'ESN35', 'ESN36',
        'ESN37', 'ESN38', 'ESN39', 'ESN40', 'ESN41', 'ESN42', 'ESN43',
        'ESN44', 'ESN45', 'ESN46', 'ESN47', 'ESN48'], dtype=object),
 'LEAP-1A26E1': array(['ESN3', 'ESN6', 'ESN8', 'ESN10', 'ESN11', 'ESN13', 'ESN17',
        'ESN19', 'ESN22', 'ESN24', 'ESN25', 'ESN26', 'ESN27', 'ESN32',
        'ESN49'], dtype=object)}

In [13]:
# Change the categorical dat types into suitable type

df['eng_number'] = df['esn'].astype('category')
df['eng_type'] = df['eng_type'].astype('category')
df['flight_phase'] = df['flight_phase'].astype('category')

In [14]:
# check the unique flight phases
df['flight_phase'].unique()

['TAKEOFF', 'CRUISE']
Categories (2, object): ['CRUISE', 'TAKEOFF']

In [15]:
# how many nulls in each flight phase
df.groupby('flight_phase', observed=False).count()

,esn,flight_datetime,aircraft_type,eng_family,eng_type,eng_install_date,cycles,delta_egt,fuel_flw,oil_temp,...,ps3_divergence,oil_pres,oil_pres_divergence,core_spd,core_spd_divergence,pt2_(fan_inlet_tot_pres),egt_probe_average,computed_air_spd,zps3,eng_number
flight_phase,,,,,,,,,,,,,,,,,,,,,
CRUISE,360103,360103,360103,360103,360103,360103,360089,351627,360068,360087,...,359954,360087,359954,360083,359954,360083,360059,360086,360087,360103
TAKEOFF,186207,186207,186207,186207,186207,186207,186191,0,186151,186186,...,186108,186189,186135,186170,186103,186181,186155,186187,186174,186207

### Initial Notes:  
1- We have 7 phases (CRUISE, CLIMB, TAKEOFF, ENGINE START, CEOD_CRUISE, CEOD_TAKEOFF, CEOD_CLIMB).  
2- From knowledge of the business domain, the critical phases (most stress) that determine engine life are takeoff, climb, and cruise.  
3- Also from business domain, each takeoff is considered one running cycle that counts into the engine remaining useful life.  
4- Flights are ordered new to old (last flight of the engine is the first on top).

In [16]:
# Keep only the critical flight phases: CRUISE, TAKEOFF, and CLIMB
df = df[df['flight_phase'].isin(['CRUISE', 'TAKEOFF'])]
df['flight_phase'] = df['flight_phase'].cat.remove_unused_categories()
print(f"Rows after filtering: {len(df)}")
print(df['flight_phase'].unique())

Rows after filtering: 546310
['TAKEOFF', 'CRUISE']
Categories (2, object): ['CRUISE', 'TAKEOFF']

In [17]:
# show the null percentage in each column
df.isnull().sum()/len(df)*100

esn                          0.000000
flight_phase                 0.000000
flight_datetime              0.000000
aircraft_type                0.000000
eng_family                   0.000000
eng_type                     0.000000
eng_install_date             0.000000
cycles                       0.005491
delta_egt                   35.635994
fuel_flw                     0.016657
oil_temp                     0.006773
egt_divergence_              0.047043
ps3_divergence               0.045395
oil_pres                     0.006224
oil_pres_divergence          0.040453
core_spd                     0.010434
core_spd_divergence          0.046311
pt2_(fan_inlet_tot_pres)     0.008420
egt_probe_average            0.017572
computed_air_spd             0.006773
zps3                         0.008969
eng_number                   0.000000
dtype: float64

In [19]:
# create date and time columns from flight_datetime (format: 'YYYY-MM-DD HH:MM:SS')
df['flight_datetime_c'] = pd.to_datetime(df['flight_datetime'], format='%Y-%m-%d %H:%M:%S')
df['date'] = df['flight_datetime_c'].dt.date
df['time'] = df['flight_datetime_c'].dt.time
df.head(30)

,esn,flight_phase,flight_datetime,aircraft_type,eng_family,eng_type,eng_install_date,cycles,delta_egt,fuel_flw,...,core_spd,core_spd_divergence,pt2_(fan_inlet_tot_pres),egt_probe_average,computed_air_spd,zps3,eng_number,flight_datetime_c,date,time
0,ESN1,TAKEOFF,2024-03-02 09:30:59,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,563.0,NaN,1716.0,...,106.45,-0.055,14.77,890.2250,88.0,470.42,ESN1,2024-03-02 09:30:59,2024-03-02,09:30:59
1,ESN1,TAKEOFF,2025-09-06 07:23:51,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,1905.0,NaN,7425.0,...,108.47,-0.080,14.11,942.5750,91.0,472.14,ESN1,2025-09-06 07:23:51,2025-09-06,07:23:51
2,ESN1,CRUISE,2025-05-04 04:32:58,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,1500.0,14.4112,2230.0,...,98.41,-0.015,4.72,699.0500,252.0,166.74,ESN1,2025-05-04 04:32:58,2025-05-04,04:32:58
3,ESN1,TAKEOFF,2025-12-17 09:57:31,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,2246.0,NaN,6619.0,...,104.47,-0.130,15.08,857.8000,90.0,444.89,ESN1,2025-12-17 09:57:31,2025-12-17,09:57:31
4,ESN1,TAKEOFF,2025-06-03 09:07:19,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,1598.0,NaN,6199.0,...,104.82,-0.090,15.03,850.2500,87.0,416.71,ESN1,2025-06-03 09:07:19,2025-06-03,09:07:19
5,ESN1,TAKEOFF,2025-10-13 15:58:02,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,2040.0,NaN,6322.0,...,105.27,-0.080,15.01,862.6000,93.0,424.15,ESN1,2025-10-13 15:58:02,2025-10-13,15:58:02
6,ESN1,TAKEOFF,2026-03-10 13:05:09,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,2471.0,NaN,6938.0,...,105.24,-0.105,14.93,871.4375,94.0,456.53,ESN1,2026-03-10 13:05:09,2026-03-10,13:05:09
7,ESN1,CRUISE,2025-10-10 08:39:27,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,2026.0,15.4168,2337.0,...,100.66,-0.015,5.44,721.3875,270.0,176.34,ESN1,2025-10-10 08:39:27,2025-10-10,08:39:27
8,ESN1,CRUISE,2024-12-06 09:07:10,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,999.0,11.7764,2157.0,...,98.66,-0.025,4.97,694.1625,259.0,164.94,ESN1,2024-12-06 09:07:10,2024-12-06,09:07:10
9,ESN1,TAKEOFF,2025-07-06 10:25:37,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,1706.0,NaN,6815.0,...,106.22,-0.155,15.02,884.4750,95.0,449.31,ESN1,2025-07-06 10:25:37,2025-07-06,10:25:37
10,ESN1,TAKEOFF,2026-01-01 16:31:39,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,2294.0,NaN,6445.0,...,104.35,-0.075,15.17,851.3125,90.0,436.46,ESN1,2026-01-01 16:31:39,2026-01-01,16:31:39
11,ESN1,TAKEOFF,2025-08-03 15:43:56,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,1789.0,NaN,7108.0,...,106.56,-0.070,15.00,899.1125,87.0,462.99,ESN1,2025-08-03 15:43:56,2025-08-03,15:43:56
12,ESN1,TAKEOFF,2024-09-04 21:38:12,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,746.0,NaN,2395.0,...,104.56,-0.055,15.04,845.8500,91.0,407.14,ESN1,2024-09-04 21:38:12,2024-09-04,21:38:12
13,ESN1,CRUISE,2026-04-05 21:52:18,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,2544.0,17.6000,2301.0,...,103.10,-0.030,4.77,787.3500,256.0,164.32,ESN1,2026-04-05 21:52:18,2026-04-05,21:52:18
14,ESN1,CRUISE,2025-08-22 16:53:48,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,1852.0,10.3734,2409.0,...,102.77,-0.030,4.94,777.6875,258.0,172.77,ESN1,2025-08-22 16:53:48,2025-08-22,16:53:48
15,ESN1,CRUISE,2025-12-09 16:54:24,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,2226.0,16.8854,2361.0,...,98.72,-0.035,5.02,706.7125,263.0,176.69,ESN1,2025-12-09 16:54:24,2025-12-09,16:54:24
16,ESN1,CRUISE,2023-11-01 13:49:06,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,209.0,9.7811,2087.0,...,98.61,-0.020,4.53,699.7750,247.0,158.63,ESN1,2023-11-01 13:49:06,2023-11-01,13:49:06
17,ESN1,CRUISE,2025-11-18 18:41:15,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,2165.0,20.1626,2482.0,...,99.14,-0.030,5.29,710.3750,272.0,186.27,ESN1,2025-11-18 18:41:15,2025-11-18,18:41:15
18,ESN1,CRUISE,2025-01-08 21:39:32,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,1115.0,11.1351,2207.0,...,100.04,-0.020,5.01,717.0500,262.0,166.98,ESN1,2025-01-08 21:39:32,2025-01-08,21:39:32
19,ESN1,TAKEOFF,2024-09-17 17:42:47,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,458.0,NaN,2847.0,...,101.73,-0.060,14.94,785.1375,89.0,416.91,ESN1,2024-09-17 17:42:47,2024-09-17,17:42:47
20,ESN1,TAKEOFF,2025-01-16 09:17:03,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,1148.0,NaN,6139.0,...,103.27,-0.065,15.34,825.7500,93.0,424.97,ESN1,2025-01-16 09:17:03,2025-01-16,09:17:03
21,ESN1,TAKEOFF,2025-04-06 08:16:05,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,1402.0,NaN,6378.0,...,105.04,-0.030,15.25,857.3250,96.0,430.36,ESN1,2025-04-06 08:16:05,2025-04-06,08:16:05
22,ESN1,CRUISE,2024-02-17 12:40:40,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,516.0,8.8456,2535.0,...,103.14,-0.010,5.50,768.8500,275.0,187.71,ESN1,2024-02-17 12:40:40,2024-02-17,12:40:40
23,ESN1,CRUISE,2024-01-01 08:15:12,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,375.0,12.9134,2410.0,...,100.61,-0.010,5.44,724.3750,270.0,184.49,ESN1,2024-01-01 08:15:12,2024-01-01,08:15:12
24,ESN1,TAKEOFF,2026-03-30 23:50:21,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,2531.0,NaN,6751.0,...,105.05,-0.095,15.14,868.9750,94.0,451.27,ESN1,2026-03-30 23:50:21,2026-03-30,23:50:21
25,ESN1,CRUISE,2025-11-10 05:28:46,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,2134.0,12.2351,2593.0,...,98.88,-0.025,7.97,704.0375,301.0,201.22,ESN1,2025-11-10 05:28:46,2025-11-10,05:28:46
26,ESN1,CRUISE,2024-12-06 13:13:23,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,1000.0,16.2662,2397.0,...,100.32,-0.020,5.44,719.4750,270.0,181.08,ESN1,2024-12-06 13:13:23,2024-12-06,13:13:23
27,ESN1,TAKEOFF,2024-10-06 06:37:46,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,848.0,NaN,1763.0,...,106.34,-0.120,14.81,896.5875,90.0,451.43,ESN1,2024-10-06 06:37:46,2024-10-06,06:37:46
28,ESN1,CRUISE,2025-05-31 03:39:15,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,1590.0,16.4922,2193.0,...,100.53,-0.020,4.77,731.8000,256.0,162.59,ESN1,2025-05-31 03:39:15,2025-05-31,03:39:15
29,ESN1,TAKEOFF,2024-09-12 11:28:56,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,772.0,NaN,2199.0,...,107.59,-0.060,14.89,915.5500,87.0,449.02,ESN1,2024-09-12 11:28:56,2024-09-12,11:28:56

In [20]:
#sort the data by engine number and flight datetime
df = df.sort_values(by=['esn', 'flight_datetime_c'])
df.head(30)

,esn,flight_phase,flight_datetime,aircraft_type,eng_family,eng_type,eng_install_date,cycles,delta_egt,fuel_flw,...,core_spd,core_spd_divergence,pt2_(fan_inlet_tot_pres),egt_probe_average,computed_air_spd,zps3,eng_number,flight_datetime_c,date,time
2527,ESN1,CRUISE,2023-09-17 12:39:46,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,48.0,NaN,2354.0,...,100.63,-0.015,5.01,729.9750,261.0,176.93,ESN1,2023-09-17 12:39:46,2023-09-17,12:39:46
1562,ESN1,TAKEOFF,2023-09-17 15:34:06,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,48.0,NaN,3239.0,...,106.53,-0.110,15.16,892.5125,86.0,482.31,ESN1,2023-09-17 15:34:06,2023-09-17,15:34:06
667,ESN1,CRUISE,2023-09-17 16:30:22,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,49.0,7.7209,2437.0,...,101.03,-0.010,5.20,734.4000,264.0,182.53,ESN1,2023-09-17 16:30:22,2023-09-17,16:30:22
3037,ESN1,TAKEOFF,2023-09-17 21:07:28,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,49.0,NaN,3412.0,...,106.63,-0.060,15.10,884.0750,88.0,448.23,ESN1,2023-09-17 21:07:28,2023-09-17,21:07:28
1064,ESN1,CRUISE,2023-09-18 00:30:03,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,50.0,4.2051,2324.0,...,100.90,-0.010,4.97,734.0000,259.0,173.72,ESN1,2023-09-18 00:30:03,2023-09-18,00:30:03
1224,ESN1,TAKEOFF,2023-09-18 03:25:01,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,50.0,NaN,3479.0,...,105.47,-0.065,15.00,864.2875,92.0,465.36,ESN1,2023-09-18 03:25:01,2023-09-18,03:25:01
4300,ESN1,CRUISE,2023-09-18 04:56:26,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,51.0,7.1666,2453.0,...,101.30,-0.005,5.21,739.1625,264.0,181.43,ESN1,2023-09-18 04:56:26,2023-09-18,04:56:26
3892,ESN1,TAKEOFF,2023-09-18 09:19:45,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,51.0,NaN,1644.0,...,105.60,-0.010,14.81,857.5625,87.0,419.40,ESN1,2023-09-18 09:19:45,2023-09-18,09:19:45
3097,ESN1,CRUISE,2023-09-18 10:15:37,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,52.0,8.1604,2264.0,...,101.83,0.000,4.56,760.6125,252.0,168.92,ESN1,2023-09-18 10:15:37,2023-09-18,10:15:37
2267,ESN1,TAKEOFF,2023-09-18 14:55:46,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,52.0,NaN,3437.0,...,106.34,-0.090,14.53,892.4000,87.0,480.36,ESN1,2023-09-18 14:55:46,2023-09-18,14:55:46
2674,ESN1,CRUISE,2023-09-19 02:59:05,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,54.0,8.4524,2271.0,...,99.53,-0.010,4.53,713.6375,249.0,161.95,ESN1,2023-09-19 02:59:05,2023-09-19,02:59:05
307,ESN1,TAKEOFF,2023-09-19 06:05:24,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,54.0,NaN,3121.0,...,103.92,-0.075,14.54,830.6375,88.0,430.90,ESN1,2023-09-19 06:05:24,2023-09-19,06:05:24
2257,ESN1,TAKEOFF,2023-09-19 12:04:11,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,55.0,NaN,1759.0,...,106.76,-0.015,14.79,885.6625,89.0,442.30,ESN1,2023-09-19 12:04:11,2023-09-19,12:04:11
745,ESN1,CRUISE,2023-09-19 14:47:56,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,56.0,10.3420,2132.0,...,99.46,-0.010,4.48,716.2375,244.0,162.11,ESN1,2023-09-19 14:47:56,2023-09-19,14:47:56
4384,ESN1,TAKEOFF,2023-09-19 17:44:18,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,56.0,NaN,3356.0,...,104.34,-0.060,15.18,836.1000,88.0,444.75,ESN1,2023-09-19 17:44:18,2023-09-19,17:44:18
4675,ESN1,TAKEOFF,2023-09-20 01:53:17,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,57.0,NaN,3111.0,...,105.19,-0.045,15.08,844.2125,90.0,422.50,ESN1,2023-09-20 01:53:17,2023-09-20,01:53:17
2472,ESN1,CRUISE,2023-09-20 02:51:09,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,58.0,6.5321,2185.0,...,100.95,-0.010,4.49,740.1000,246.0,159.61,ESN1,2023-09-20 02:51:09,2023-09-20,02:51:09
586,ESN1,TAKEOFF,2023-09-20 07:03:42,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,58.0,NaN,3636.0,...,105.43,-0.065,15.06,866.2750,89.0,473.20,ESN1,2023-09-20 07:03:42,2023-09-20,07:03:42
257,ESN1,CRUISE,2023-09-20 09:06:52,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,59.0,7.1570,2527.0,...,101.23,-0.010,5.31,736.9375,272.0,185.03,ESN1,2023-09-20 09:06:52,2023-09-20,09:06:52
2228,ESN1,TAKEOFF,2023-09-20 12:35:07,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,59.0,NaN,1668.0,...,106.19,-0.075,14.73,870.4875,92.0,437.13,ESN1,2023-09-20 12:35:07,2023-09-20,12:35:07
2010,ESN1,CRUISE,2023-09-20 14:04:55,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,60.0,4.1678,2357.0,...,100.63,-0.005,4.95,730.1625,258.0,174.40,ESN1,2023-09-20 14:04:55,2023-09-20,14:04:55
3911,ESN1,TAKEOFF,2023-09-20 18:10:30,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,60.0,NaN,3118.0,...,105.03,-0.085,14.91,852.7750,86.0,440.66,ESN1,2023-09-20 18:10:30,2023-09-20,18:10:30
278,ESN1,TAKEOFF,2023-09-21 05:41:45,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,61.0,NaN,1653.0,...,105.75,-0.025,14.86,866.7500,90.0,448.04,ESN1,2023-09-21 05:41:45,2023-09-21,05:41:45
1964,ESN1,CRUISE,2023-09-21 08:23:06,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,62.0,3.8405,2206.0,...,99.42,-0.025,4.98,700.9250,259.0,166.15,ESN1,2023-09-21 08:23:06,2023-09-21,08:23:06
2112,ESN1,TAKEOFF,2023-09-21 12:34:07,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,62.0,NaN,3314.0,...,107.43,-0.085,14.92,915.9875,86.0,502.29,ESN1,2023-09-21 12:34:07,2023-09-21,12:34:07
4003,ESN1,CRUISE,2023-09-21 13:20:19,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,63.0,NaN,2587.0,...,101.41,-0.015,5.28,746.2625,272.0,192.71,ESN1,2023-09-21 13:20:19,2023-09-21,13:20:19
3504,ESN1,TAKEOFF,2023-09-21 19:11:36,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,63.0,NaN,3403.0,...,106.12,-0.055,15.19,868.9750,90.0,439.71,ESN1,2023-09-21 19:11:36,2023-09-21,19:11:36
4672,ESN1,CRUISE,2023-09-21 23:06:01,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,64.0,7.4911,2299.0,...,99.85,-0.015,4.95,716.5250,258.0,174.12,ESN1,2023-09-21 23:06:01,2023-09-21,23:06:01
656,ESN1,TAKEOFF,2023-09-22 01:13:27,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,64.0,NaN,3179.0,...,104.82,-0.095,14.95,852.3625,91.0,470.74,ESN1,2023-09-22 01:13:27,2023-09-22,01:13:27
3308,ESN1,TAKEOFF,2023-09-22 08:12:56,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,65.0,NaN,2057.0,...,106.06,-0.085,15.03,871.4250,90.0,439.69,ESN1,2023-09-22 08:12:56,2023-09-22,08:12:56

In [21]:
# drop the flight_datetime column
df = df.drop('flight_datetime', axis=1)

In [22]:
# for each engine lets assign a flight cycle for each row, flight cycle start with take off and end with cruise
# flight cycle will increase by 1 for each take off from oldest to newest date for each engine
# first split daata by engine into a list of dataframes 
# then from oldest to newsest date for each engine assign a flight cycle for each row that increaes by 1 for each take off
# then combine the dataframes into one dataframe
df['flight_cycle'] = 0
df_list = [df[df['esn'] == i] for i in df['esn'].unique()]
for i in range(len(df_list)):
    df_list[i] = df_list[i].sort_values(by='flight_datetime_c')
    flight_cycle = 0
    for j in range(len(df_list[i])):
        if df_list[i].iloc[j]['flight_phase'] == 'TAKEOFF':
            flight_cycle += 1
        df_list[i].iloc[j, df_list[i].columns.get_loc('flight_cycle')] = flight_cycle

In [23]:
# combine the dataframes
df = pd.concat(df_list)

In [24]:
df.head(20)

,esn,flight_phase,aircraft_type,eng_family,eng_type,eng_install_date,cycles,delta_egt,fuel_flw,oil_temp,...,core_spd_divergence,pt2_(fan_inlet_tot_pres),egt_probe_average,computed_air_spd,zps3,eng_number,flight_datetime_c,date,time,flight_cycle
2527,ESN1,CRUISE,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,48.0,NaN,2354.0,83.5,...,-0.015,5.01,729.9750,261.0,176.93,ESN1,2023-09-17 12:39:46,2023-09-17,12:39:46,0
1562,ESN1,TAKEOFF,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,48.0,NaN,3239.0,87.8,...,-0.110,15.16,892.5125,86.0,482.31,ESN1,2023-09-17 15:34:06,2023-09-17,15:34:06,1
667,ESN1,CRUISE,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,49.0,7.7209,2437.0,90.0,...,-0.010,5.20,734.4000,264.0,182.53,ESN1,2023-09-17 16:30:22,2023-09-17,16:30:22,1
3037,ESN1,TAKEOFF,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,49.0,NaN,3412.0,93.0,...,-0.060,15.10,884.0750,88.0,448.23,ESN1,2023-09-17 21:07:28,2023-09-17,21:07:28,2
1064,ESN1,CRUISE,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,50.0,4.2051,2324.0,84.7,...,-0.010,4.97,734.0000,259.0,173.72,ESN1,2023-09-18 00:30:03,2023-09-18,00:30:03,2
1224,ESN1,TAKEOFF,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,50.0,NaN,3479.0,83.2,...,-0.065,15.00,864.2875,92.0,465.36,ESN1,2023-09-18 03:25:01,2023-09-18,03:25:01,3
4300,ESN1,CRUISE,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,51.0,7.1666,2453.0,87.8,...,-0.005,5.21,739.1625,264.0,181.43,ESN1,2023-09-18 04:56:26,2023-09-18,04:56:26,3
3892,ESN1,TAKEOFF,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,51.0,NaN,1644.0,86.7,...,-0.010,14.81,857.5625,87.0,419.40,ESN1,2023-09-18 09:19:45,2023-09-18,09:19:45,4
3097,ESN1,CRUISE,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,52.0,8.1604,2264.0,98.5,...,0.000,4.56,760.6125,252.0,168.92,ESN1,2023-09-18 10:15:37,2023-09-18,10:15:37,4
2267,ESN1,TAKEOFF,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,52.0,NaN,3437.0,84.6,...,-0.090,14.53,892.4000,87.0,480.36,ESN1,2023-09-18 14:55:46,2023-09-18,14:55:46,5
2674,ESN1,CRUISE,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,54.0,8.4524,2271.0,85.0,...,-0.010,4.53,713.6375,249.0,161.95,ESN1,2023-09-19 02:59:05,2023-09-19,02:59:05,5
307,ESN1,TAKEOFF,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,54.0,NaN,3121.0,83.0,...,-0.075,14.54,830.6375,88.0,430.90,ESN1,2023-09-19 06:05:24,2023-09-19,06:05:24,6
2257,ESN1,TAKEOFF,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,55.0,NaN,1759.0,93.9,...,-0.015,14.79,885.6625,89.0,442.30,ESN1,2023-09-19 12:04:11,2023-09-19,12:04:11,7
745,ESN1,CRUISE,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,56.0,10.3420,2132.0,85.2,...,-0.010,4.48,716.2375,244.0,162.11,ESN1,2023-09-19 14:47:56,2023-09-19,14:47:56,7
4384,ESN1,TAKEOFF,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,56.0,NaN,3356.0,81.2,...,-0.060,15.18,836.1000,88.0,444.75,ESN1,2023-09-19 17:44:18,2023-09-19,17:44:18,8
4675,ESN1,TAKEOFF,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,57.0,NaN,3111.0,87.8,...,-0.045,15.08,844.2125,90.0,422.50,ESN1,2023-09-20 01:53:17,2023-09-20,01:53:17,9
2472,ESN1,CRUISE,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,58.0,6.5321,2185.0,97.0,...,-0.010,4.49,740.1000,246.0,159.61,ESN1,2023-09-20 02:51:09,2023-09-20,02:51:09,9
586,ESN1,TAKEOFF,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,58.0,NaN,3636.0,81.0,...,-0.065,15.06,866.2750,89.0,473.20,ESN1,2023-09-20 07:03:42,2023-09-20,07:03:42,10
257,ESN1,CRUISE,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,59.0,7.1570,2527.0,85.0,...,-0.010,5.31,736.9375,272.0,185.03,ESN1,2023-09-20 09:06:52,2023-09-20,09:06:52,10
2228,ESN1,TAKEOFF,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,59.0,NaN,1668.0,88.8,...,-0.075,14.73,870.4875,92.0,437.13,ESN1,2023-09-20 12:35:07,2023-09-20,12:35:07,11

In [ ]:
# --- RCL with policy-based removal threshold ---
# Fleet operating policy: engines are removed at POLICY_REMOVAL_CYCLE cycles.
#
# expected_max_cycle per engine:
#   - removed engine that came off below policy: keep observed max_cycle
#     (the engine genuinely retired at fewer cycles)
#   - removed engine that came off above policy: cap at policy
#   - active engine: assume policy threshold (the planned removal point)
#
# This unifies the labels across the whole fleet under a single auditable
# threshold, replacing the earlier empirical-prior approach (which depended
# on the small sample of off-wing engines).

REMOVAL_THRESHOLD_DAYS = 21
POLICY_REMOVAL_CYCLE = 5000

df['flight_datetime_c'] = pd.to_datetime(df['flight_datetime_c'])
last_obs   = df.groupby('esn')['flight_datetime_c'].max()
max_cycles = df.groupby('esn')['flight_cycle'].max()
cutoff = df['flight_datetime_c'].max()
days_since_last = (cutoff - last_obs).dt.days
is_removed = days_since_last >= REMOVAL_THRESHOLD_DAYS

# Apply the policy: cap at POLICY_REMOVAL_CYCLE for engines past it,
# otherwise use observed max_cycle for removed engines, or POLICY_REMOVAL_CYCLE for active.
expected_max = {}
for esn in df['esn'].unique():
    if is_removed.get(esn, False):
        expected_max[esn] = float(min(POLICY_REMOVAL_CYCLE, max_cycles[esn]))
    else:
        expected_max[esn] = float(POLICY_REMOVAL_CYCLE)

print(f"Policy removal cycle: {POLICY_REMOVAL_CYCLE}")
print(f"Removed engines: {int(is_removed.sum())} / {len(is_removed)}")
print(f"expected_max distribution:")
print(pd.Series(expected_max).value_counts().sort_index())

# RCL using the policy-aware anchor, clipped at 0.
df['RCL'] = (df['esn'].map(expected_max) - df['flight_cycle']).clip(lower=0)
max_flight_cycle = max_cycles.to_dict()
df['is_engine_active'] = (~df['esn'].map(is_removed)).astype(int)
df['expected_max_cycle'] = df['esn'].map(expected_max)

print(f"\nRCL summary after policy correction:")
print(df['RCL'].describe())

In [26]:
# lets check the data
df.head(20)

,esn,flight_phase,aircraft_type,eng_family,eng_type,eng_install_date,cycles,delta_egt,fuel_flw,oil_temp,...,pt2_(fan_inlet_tot_pres),egt_probe_average,computed_air_spd,zps3,eng_number,flight_datetime_c,date,time,flight_cycle,RCL
2527,ESN1,CRUISE,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,48.0,NaN,2354.0,83.5,...,5.01,729.9750,261.0,176.93,ESN1,2023-09-17 12:39:46,2023-09-17,12:39:46,0,2602
1562,ESN1,TAKEOFF,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,48.0,NaN,3239.0,87.8,...,15.16,892.5125,86.0,482.31,ESN1,2023-09-17 15:34:06,2023-09-17,15:34:06,1,2601
667,ESN1,CRUISE,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,49.0,7.7209,2437.0,90.0,...,5.20,734.4000,264.0,182.53,ESN1,2023-09-17 16:30:22,2023-09-17,16:30:22,1,2601
3037,ESN1,TAKEOFF,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,49.0,NaN,3412.0,93.0,...,15.10,884.0750,88.0,448.23,ESN1,2023-09-17 21:07:28,2023-09-17,21:07:28,2,2600
1064,ESN1,CRUISE,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,50.0,4.2051,2324.0,84.7,...,4.97,734.0000,259.0,173.72,ESN1,2023-09-18 00:30:03,2023-09-18,00:30:03,2,2600
1224,ESN1,TAKEOFF,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,50.0,NaN,3479.0,83.2,...,15.00,864.2875,92.0,465.36,ESN1,2023-09-18 03:25:01,2023-09-18,03:25:01,3,2599
4300,ESN1,CRUISE,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,51.0,7.1666,2453.0,87.8,...,5.21,739.1625,264.0,181.43,ESN1,2023-09-18 04:56:26,2023-09-18,04:56:26,3,2599
3892,ESN1,TAKEOFF,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,51.0,NaN,1644.0,86.7,...,14.81,857.5625,87.0,419.40,ESN1,2023-09-18 09:19:45,2023-09-18,09:19:45,4,2598
3097,ESN1,CRUISE,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,52.0,8.1604,2264.0,98.5,...,4.56,760.6125,252.0,168.92,ESN1,2023-09-18 10:15:37,2023-09-18,10:15:37,4,2598
2267,ESN1,TAKEOFF,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,52.0,NaN,3437.0,84.6,...,14.53,892.4000,87.0,480.36,ESN1,2023-09-18 14:55:46,2023-09-18,14:55:46,5,2597
2674,ESN1,CRUISE,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,54.0,8.4524,2271.0,85.0,...,4.53,713.6375,249.0,161.95,ESN1,2023-09-19 02:59:05,2023-09-19,02:59:05,5,2597
307,ESN1,TAKEOFF,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,54.0,NaN,3121.0,83.0,...,14.54,830.6375,88.0,430.90,ESN1,2023-09-19 06:05:24,2023-09-19,06:05:24,6,2596
2257,ESN1,TAKEOFF,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,55.0,NaN,1759.0,93.9,...,14.79,885.6625,89.0,442.30,ESN1,2023-09-19 12:04:11,2023-09-19,12:04:11,7,2595
745,ESN1,CRUISE,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,56.0,10.3420,2132.0,85.2,...,4.48,716.2375,244.0,162.11,ESN1,2023-09-19 14:47:56,2023-09-19,14:47:56,7,2595
4384,ESN1,TAKEOFF,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,56.0,NaN,3356.0,81.2,...,15.18,836.1000,88.0,444.75,ESN1,2023-09-19 17:44:18,2023-09-19,17:44:18,8,2594
4675,ESN1,TAKEOFF,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,57.0,NaN,3111.0,87.8,...,15.08,844.2125,90.0,422.50,ESN1,2023-09-20 01:53:17,2023-09-20,01:53:17,9,2593
2472,ESN1,CRUISE,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,58.0,6.5321,2185.0,97.0,...,4.49,740.1000,246.0,159.61,ESN1,2023-09-20 02:51:09,2023-09-20,02:51:09,9,2593
586,ESN1,TAKEOFF,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,58.0,NaN,3636.0,81.0,...,15.06,866.2750,89.0,473.20,ESN1,2023-09-20 07:03:42,2023-09-20,07:03:42,10,2592
257,ESN1,CRUISE,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,59.0,7.1570,2527.0,85.0,...,5.31,736.9375,272.0,185.03,ESN1,2023-09-20 09:06:52,2023-09-20,09:06:52,10,2592
2228,ESN1,TAKEOFF,A320neo,LEAP-1A,LEAP-1A26,2023-09-01 23:00:00,59.0,NaN,1668.0,88.8,...,14.73,870.4875,92.0,437.13,ESN1,2023-09-20 12:35:07,2023-09-20,12:35:07,11,2591

In [27]:
max_flight_cycle

{'ESN1': np.int64(2602),
 'ESN10': np.int64(5266),
 'ESN11': np.int64(5996),
 'ESN12': np.int64(3720),
 'ESN13': np.int64(4562),
 'ESN14': np.int64(5462),
 'ESN15': np.int64(2007),
 'ESN16': np.int64(4074),
 'ESN17': np.int64(4149),
 'ESN18': np.int64(1557),
 'ESN19': np.int64(4281),
 'ESN2': np.int64(4074),
 'ESN20': np.int64(4967),
 'ESN21': np.int64(1557),
 'ESN22': np.int64(6038),
 'ESN23': np.int64(1397),
 'ESN24': np.int64(4843),
 'ESN25': np.int64(5153),
 'ESN26': np.int64(6065),
 'ESN27': np.int64(4356),
 'ESN28': np.int64(3879),
 'ESN29': np.int64(3879),
 'ESN3': np.int64(5712),
 'ESN30': np.int64(4204),
 'ESN31': np.int64(3358),
 'ESN32': np.int64(3578),
 'ESN33': np.int64(4204),
 'ESN34': np.int64(1450),
 'ESN35': np.int64(1756),
 'ESN36': np.int64(4421),
 'ESN37': np.int64(4421),
 'ESN38': np.int64(3358),
 'ESN39': np.int64(3634),
 'ESN4': np.int64(4209),
 'ESN40': np.int64(4506),
 'ESN41': np.int64(2602),
 'ESN42': np.int64(1638),
 'ESN43': np.int64(4506),
 'ESN44': np.int64(5017),
 'ESN45': np.int64(3319),
 'ESN46': np.int64(3319),
 'ESN47': np.int64(3720),
 'ESN48': np.int64(3705),
 'ESN49': np.int64(5297),
 'ESN5': np.int64(1397),
 'ESN6': np.int64(4962),
 'ESN7': np.int64(1756),
 'ESN8': np.int64(4636),
 'ESN9': np.int64(1638)}

In [28]:
# lets add  max_flight_cycle dict to the engine life dict in days
engine_life = {}
for i in df['eng_number'].unique():
    engine_life[i] = (df[df['eng_number'] == i]['date'].max() - df[df['eng_number'] == i]['date'].min()).days

# Add max_flight_cycle to engine_life
for i in engine_life.keys():
    engine_life[i] = {'Life in Days': engine_life[i], 'Life in FC': max_flight_cycle[i]}
engine_life

{'ESN1': {'Life in Days': 958, 'Life in FC': np.int64(2602)},
 'ESN10': {'Life in Days': 2243, 'Life in FC': np.int64(5266)},
 'ESN11': {'Life in Days': 2088, 'Life in FC': np.int64(5996)},
 'ESN12': {'Life in Days': 1001, 'Life in FC': np.int64(3720)},
 'ESN13': {'Life in Days': 2223, 'Life in FC': np.int64(4562)},
 'ESN14': {'Life in Days': 1675, 'Life in FC': np.int64(5462)},
 'ESN15': {'Life in Days': 734, 'Life in FC': np.int64(2007)},
 'ESN16': {'Life in Days': 1187, 'Life in FC': np.int64(4074)},
 'ESN17': {'Life in Days': 1200, 'Life in FC': np.int64(4149)},
 'ESN18': {'Life in Days': 608, 'Life in FC': np.int64(1557)},
 'ESN19': {'Life in Days': 1275, 'Life in FC': np.int64(4281)},
 'ESN2': {'Life in Days': 1187, 'Life in FC': np.int64(4074)},
 'ESN20': {'Life in Days': 1575, 'Life in FC': np.int64(4967)},
 'ESN21': {'Life in Days': 608, 'Life in FC': np.int64(1557)},
 'ESN22': {'Life in Days': 2243, 'Life in FC': np.int64(6038)},
 'ESN23': {'Life in Days': 547, 'Life in FC': np.int64(1397)},
 'ESN24': {'Life in Days': 1366, 'Life in FC': np.int64(4843)},
 'ESN25': {'Life in Days': 2066, 'Life in FC': np.int64(5153)},
 'ESN26': {'Life in Days': 2254, 'Life in FC': np.int64(6065)},
 'ESN27': {'Life in Days': 2087, 'Life in FC': np.int64(4356)},
 'ESN28': {'Life in Days': 1132, 'Life in FC': np.int64(3879)},
 'ESN29': {'Life in Days': 1132, 'Life in FC': np.int64(3879)},
 'ESN3': {'Life in Days': 2067, 'Life in FC': np.int64(5712)},
 'ESN30': {'Life in Days': 1232, 'Life in FC': np.int64(4204)},
 'ESN31': {'Life in Days': 1114, 'Life in FC': np.int64(3358)},
 'ESN32': {'Life in Days': 1054, 'Life in FC': np.int64(3578)},
 'ESN33': {'Life in Days': 1232, 'Life in FC': np.int64(4204)},
 'ESN34': {'Life in Days': 450, 'Life in FC': np.int64(1450)},
 'ESN35': {'Life in Days': 602, 'Life in FC': np.int64(1756)},
 'ESN36': {'Life in Days': 1284, 'Life in FC': np.int64(4421)},
 'ESN37': {'Life in Days': 1284, 'Life in FC': np.int64(4421)},
 'ESN38': {'Life in Days': 1114, 'Life in FC': np.int64(3358)},
 'ESN39': {'Life in Days': 1072, 'Life in FC': np.int64(3634)},
 'ESN4': {'Life in Days': 1756, 'Life in FC': np.int64(4209)},
 'ESN40': {'Life in Days': 1284, 'Life in FC': np.int64(4506)},
 'ESN41': {'Life in Days': 958, 'Life in FC': np.int64(2602)},
 'ESN42': {'Life in Days': 534, 'Life in FC': np.int64(1638)},
 'ESN43': {'Life in Days': 1284, 'Life in FC': np.int64(4506)},
 'ESN44': {'Life in Days': 1756, 'Life in FC': np.int64(5017)},
 'ESN45': {'Life in Days': 1183, 'Life in FC': np.int64(3319)},
 'ESN46': {'Life in Days': 1183, 'Life in FC': np.int64(3319)},
 'ESN47': {'Life in Days': 1001, 'Life in FC': np.int64(3720)},
 'ESN48': {'Life in Days': 1469, 'Life in FC': np.int64(3705)},
 'ESN49': {'Life in Days': 2254, 'Life in FC': np.int64(5297)},
 'ESN5': {'Life in Days': 547, 'Life in FC': np.int64(1397)},
 'ESN6': {'Life in Days': 2067, 'Life in FC': np.int64(4962)},
 'ESN7': {'Life in Days': 602, 'Life in FC': np.int64(1756)},
 'ESN8': {'Life in Days': 2067, 'Life in FC': np.int64(4636)},
 'ESN9': {'Life in Days': 534, 'Life in FC': np.int64(1638)}}

## Combine Engine Types: Baseline Normalisation + One-Hot Encoding

The EDA confirmed that `LEAP-1A26` and `LEAP-1A26E1` share essentially the same operating envelope (11/12 feature/phase comparisons within 5% of each other; only `fuel_flw` in TAKEOFF diverges by ~24%, the known E1 fuel-burn improvement).

To merge both types into one training set without confounding type-offset with degradation, we add two preprocessing steps before saving:

1. **Per-engine baseline normalisation:** for each engine, subtract its first-50-flight-cycles mean per phase per feature. The result (suffix `_norm`) is a drift signal centred on each engine's own healthy baseline, so absolute level differences between -1A26 and -1A26E1 disappear.
2. **One-hot encoding of `eng_type`:** lets sequence models retain the type label as a feature without it leaking through the numeric sensor channels.

In [ ]:
# Per-engine baseline normalisation (first N flight cycles per phase)
import numpy as np
import pandas as pd

baseline_cycles = 50  # first 50 cycles considered "healthy baseline"
sensor_features = ['egt_probe_average', 'fuel_flw', 'core_spd', 'oil_temp', 'oil_pres', 'pt2_(fan_inlet_tot_pres)']

def add_baseline_normalised(df, features, n_cycles=50):
    df = df.copy()
    for feat in features:
        df[f'{feat}_norm'] = np.nan
    for esn in df['esn'].unique():
        for phase in df['flight_phase'].cat.categories if hasattr(df['flight_phase'], 'cat') else df['flight_phase'].unique():
            mask = (df['esn'] == esn) & (df['flight_phase'] == phase)
            sub = df.loc[mask].sort_values('flight_cycle')
            if sub.empty:
                continue
            baseline = sub[sub['flight_cycle'] <= n_cycles][features].mean()
            for feat in features:
                df.loc[mask, f'{feat}_norm'] = df.loc[mask, feat] - baseline[feat]
    return df

df = add_baseline_normalised(df, sensor_features, n_cycles=baseline_cycles)
print(f"Added {len(sensor_features)} baseline-normalised columns (suffix _norm).")
print(df[[f'{f}_norm' for f in sensor_features]].describe().round(2))

In [ ]:
# One-hot encode eng_type so the model can keep the type label without it bleeding into sensor channels
eng_type_dummies = pd.get_dummies(df['eng_type'].astype(str), prefix='engtype').astype(int)
df = pd.concat([df, eng_type_dummies], axis=1)
print("Added one-hot columns:", list(eng_type_dummies.columns))
print(df[list(eng_type_dummies.columns)].sum())

In [29]:
# save the cleaned data to a csv file
df.to_csv('Data/LEAB_engines_data_cleaned.csv', index=False)